### ISSUE TITLE
Classification Task 질문 드립니다!! 

### ISSUE THREAD

**Issue by hys50001** [hyunwoongko/kobart-transformers#2]
안녕하세요.
우선 좋은 자료 공유해주셔서 감사드립니다. 

제가 KoBART 모델로 Classification Task를 해보려고 
Huggingface Transformers의 BartForSequenceClassification 에 올려주신 모델을 임포트 해서 사용하려는데
호환이 잘 안되는 것 같더라구요 ..

아마 Decoder의 pooled output 을 classification linear layer 로 input 시키는 데에 문제가 발생하는 것 같은데
혹시 확인가능할까요!?  

감사합니다

**Comment by hyunwoongko** [comment]
안녕하세요~ 에러 로그를 정확히 보여주실 수 있으실까요?

**Comment by hys50001** [comment]
![image](https://user-images.githubusercontent.com/75110162/103190420-37d7df80-4914-11eb-9b0c-9b3e30ac986c.png)

이거 입니다!

**Comment by hyunwoongko** [comment]
보니까 로드하는 부분이 아니라 forward 함수에서 에러가 발생했네요. 
실행하신 코드 올려주시면 에러 재현해볼게요!

**Comment by hys50001** [comment]
![image](https://user-images.githubusercontent.com/75110162/103218897-a42c0080-495f-11eb-87e5-4699b46879a2.png)


!pip install transformers==4.1.1
import transformers
from transformers import BartForSequenceClassification,PreTrainedTokenizerFast
import numpy as np
import torch

tokenizer = PreTrainedTokenizerFast.from_pretrained("hyunwoongko/kobart")
model = BartForSequenceClassification.from_pretrained("hyunwoongko/kobart")

text = '안녕하세요'
inputs = tokenizer(text,return_tensors="pt")
input_ids = inputs['input_ids']
attention_mask = inputs['attention_mask']
model(input_ids=input_ids, attention_mask=attention_mask)


회신이 조금 늦었네요 ㅜ

**Comment by haven-jeon** [comment]
@hys50001 KoBART를 이용한 NSMC 분류 예제코드를 올려뒀는데,  https://github.com/SKT-AI/KoBART/blob/5c6464256ac74c45b684a920e48a1dda18a6b35f/examples/nsmc.py#L76 클래스가 도움이 될거 같네요. ^^

**Comment by hys50001** [comment]
아하 덕분에 잘 해결했습니다 감사합니다!
